package scc.portal.model.viewObject;

import java.sql.ResultSet;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 05 02:37:52 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CasesVO_HSImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CasesVO_HSImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }


    /**
     * Returns the variable value for COURT_TYPE_NAME.
     * @return variable value for COURT_TYPE_NAME
     */
    public String getCOURT_TYPE_NAME() {
        return (String)ensureVariableManager().getVariableValue("COURT_TYPE_NAME");
    }

    /**
     * Sets <code>value</code> for variable COURT_TYPE_NAME.
     * @param value value to bind as COURT_TYPE_NAME
     */
    public void setCOURT_TYPE_NAME(String value) {
        ensureVariableManager().setVariableValue("COURT_TYPE_NAME", value);
    }

    /**
     * Returns the variable value for RULE_SUBJECT_TYPE_NAME.
     * @return variable value for RULE_SUBJECT_TYPE_NAME
     */
    public String getRULE_SUBJECT_TYPE_NAME() {
        return (String)ensureVariableManager().getVariableValue("RULE_SUBJECT_TYPE_NAME");
    }

    /**
     * Sets <code>value</code> for variable RULE_SUBJECT_TYPE_NAME.
     * @param value value to bind as RULE_SUBJECT_TYPE_NAME
     */
    public void setRULE_SUBJECT_TYPE_NAME(String value) {
        ensureVariableManager().setVariableValue("RULE_SUBJECT_TYPE_NAME", value);
    }

    /**
     * Returns the variable value for RULE_NUMBER.
     * @return variable value for RULE_NUMBER
     */
    public Number getRULE_NUMBER() {
        return (Number)ensureVariableManager().getVariableValue("RULE_NUMBER");
    }

    /**
     * Sets <code>value</code> for variable RULE_NUMBER.
     * @param value value to bind as RULE_NUMBER
     */
    public void setRULE_NUMBER(Number value) {
        ensureVariableManager().setVariableValue("RULE_NUMBER", value);
    }

    /**
     * Returns the variable value for COURT_YEAR.
     * @return variable value for COURT_YEAR
     */
    public Number getCOURT_YEAR() {
        return (Number)ensureVariableManager().getVariableValue("COURT_YEAR");
    }

    /**
     * Sets <code>value</code> for variable COURT_YEAR.
     * @param value value to bind as COURT_YEAR
     */
    public void setCOURT_YEAR(Number value) {
        ensureVariableManager().setVariableValue("COURT_YEAR", value);
    }

    /**
     * Returns the variable value for Claimed_name.
     * @return variable value for Claimed_name
     */
    public String getClaimed_name() {
        return (String)ensureVariableManager().getVariableValue("Claimed_name");
    }

    /**
     * Sets <code>value</code> for variable Claimed_name.
     * @param value value to bind as Claimed_name
     */
    public void setClaimed_name(String value) {
        ensureVariableManager().setVariableValue("Claimed_name", value);
    }

    /**
     * Returns the variable value for Defendant_name.
     * @return variable value for Defendant_name
     */
    public String getDefendant_name() {
        return (String)ensureVariableManager().getVariableValue("Defendant_name");
    }

    /**
     * Sets <code>value</code> for variable Defendant_name.
     * @param value value to bind as Defendant_name
     */
    public void setDefendant_name(String value) {
        ensureVariableManager().setVariableValue("Defendant_name", value);
    }
}
