package scc.portal.model.viewObject;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCIteratorBinding;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 21 15:49:35 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Court_Members_Current_VO_SDImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Court_Members_Current_VO_SDImpl() {
        
                  
              
    }
    
}
