package scc.portal.model.viewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 26 22:56:50 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MofwadeenVO_SDImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MofwadeenVO_SDImpl() {
    }
}
